@startuml activity
!theme plain
title TDMS - Creating and Using a Table

start

:Open TDMS;

if (Need existing data?) then (yes)
  if (From Google Drive?) then (yes)
    :Connect to Google;
    :Select file;
    :Download database;
  else (no)
    :Open local file;
  endif
else (no)
  :Create new database;
endif

:Choose what to do;

if (Create table?) then (yes)
  :Enter table name;
  :Add columns;
  repeat
    :Column name;
    :Column type;
    
  repeat while (More columns?)
  :Create table;
  
  :Add data;
  repeat
    :Enter values;
    :Validate types;
    :Insert row;
  repeat while (More rows?)
  
elseif (Union tables?) then (yes)
  :Select first table;
  :Select second table;
  :Check compatibility;
  :Combine tables;
  :Show result;
else (view)
  :Select table;
  :Display contents;
endif

:Save work;
if (Save to cloud?) then (yes)
  :Upload to Google Drive;
else (no)
  :Save locally;
endif

stop

@enduml